<?php

namespace ContainerPUetu1R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DxkX6ZNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DxkX6ZN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DxkX6ZN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            '_userService' => ['privates', 'App\\Service\\UserService', 'getUserServiceService', true],
            'encoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'profil' => ['privates', 'App\\Repository\\ProfileRepository', 'getProfileRepositoryService', true],
            'serializer' => ['services', 'serializer', 'getSerializerService', false],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'validator' => ['services', 'validator', 'getValidatorService', false],
        ], [
            '_userService' => 'App\\Service\\UserService',
            'encoder' => '?',
            'manager' => '?',
            'profil' => 'App\\Repository\\ProfileRepository',
            'serializer' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
            'validator' => '?',
        ]);
    }
}
