<?php

namespace ContainerUqqvH5F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9eJSN7iService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9eJSN7i' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9eJSN7i'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'CriterAdmission' => ['privates', 'App\\Repository\\CritereAdmissionRepository', 'getCritereAdmissionRepositoryService', true],
            'CritereEvaluation' => ['privates', 'App\\Repository\\CritereEvaluationRepository', 'getCritereEvaluationRepositoryService', true],
            'GrpCompetences' => ['privates', 'App\\Repository\\GrpCompetencesRepository', 'getGrpCompetencesRepositoryService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'serializer' => ['services', 'serializer', 'getSerializerService', false],
            'validator' => ['services', 'validator', 'getValidatorService', false],
        ], [
            'CriterAdmission' => 'App\\Repository\\CritereAdmissionRepository',
            'CritereEvaluation' => 'App\\Repository\\CritereEvaluationRepository',
            'GrpCompetences' => 'App\\Repository\\GrpCompetencesRepository',
            'manager' => '?',
            'serializer' => '?',
            'validator' => '?',
        ]);
    }
}
