<?php

namespace ContainerUqqvH5F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NWE6WNnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nWE6WNn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nWE6WNn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Promo' => ['privates', 'App\\Repository\\PromoRepository', 'getPromoRepositoryService', true],
            'fabrique' => ['privates', 'App\\Repository\\FabriqueRepository', 'getFabriqueRepositoryService', true],
            'langue' => ['privates', 'App\\Repository\\LangueRepository', 'getLangueRepositoryService', true],
            'mailer' => ['services', 'swiftmailer.mailer.default', 'getSwiftmailer_Mailer_DefaultService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'referentiel' => ['privates', 'App\\Repository\\ReferentielRepository', 'getReferentielRepositoryService', true],
            'serializer' => ['services', 'serializer', 'getSerializerService', false],
            'validator' => ['services', 'validator', 'getValidatorService', false],
        ], [
            'Promo' => 'App\\Repository\\PromoRepository',
            'fabrique' => 'App\\Repository\\FabriqueRepository',
            'langue' => 'App\\Repository\\LangueRepository',
            'mailer' => '?',
            'manager' => '?',
            'referentiel' => 'App\\Repository\\ReferentielRepository',
            'serializer' => '?',
            'validator' => '?',
        ]);
    }
}
