<?php

namespace ContainerUqqvH5F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y8flCfdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.y8flCfd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.y8flCfd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ApiController::ApprenantAddedByFormateur' => ['privates', '.service_locator.DxkX6ZN', 'get_ServiceLocator_DxkX6ZNService', true],
            'App\\Controller\\ApiController::GroupeCompetence' => ['privates', '.service_locator.VJywsi3', 'get_ServiceLocator_VJywsi3Service', true],
            'App\\Controller\\ApiController::UpdatePormo' => ['privates', '.service_locator.laXNkD5', 'get_ServiceLocator_LaXNkD5Service', true],
            'App\\Controller\\ApiController::UpdateReferentiel' => ['privates', '.service_locator.laXNkD5', 'get_ServiceLocator_LaXNkD5Service', true],
            'App\\Controller\\ApiController::addGroupTag' => ['privates', '.service_locator.CFXoCYH', 'get_ServiceLocator_CFXoCYHService', true],
            'App\\Controller\\ApiController::addPromo' => ['privates', '.service_locator.nWE6WNn', 'get_ServiceLocator_NWE6WNnService', true],
            'App\\Controller\\ApiController::addREferentiels' => ['privates', '.service_locator.9eJSN7i', 'get_ServiceLocator_9eJSN7iService', true],
            'App\\Controller\\ApiController::addUser' => ['privates', '.service_locator.DxkX6ZN', 'get_ServiceLocator_DxkX6ZNService', true],
            'App\\Controller\\ApiController::editUser' => ['privates', '.service_locator..BC20In', 'get_ServiceLocator__BC20InService', true],
            'App\\Controller\\LivrablesController::UpdateLivrable' => ['privates', '.service_locator.19ps0qC', 'get_ServiceLocator_19ps0qCService', true],
            'App\\Controller\\LivrablesController::addLivrable' => ['privates', '.service_locator.19ps0qC', 'get_ServiceLocator_19ps0qCService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\ApiController:ApprenantAddedByFormateur' => ['privates', '.service_locator.DxkX6ZN', 'get_ServiceLocator_DxkX6ZNService', true],
            'App\\Controller\\ApiController:GroupeCompetence' => ['privates', '.service_locator.VJywsi3', 'get_ServiceLocator_VJywsi3Service', true],
            'App\\Controller\\ApiController:UpdatePormo' => ['privates', '.service_locator.laXNkD5', 'get_ServiceLocator_LaXNkD5Service', true],
            'App\\Controller\\ApiController:UpdateReferentiel' => ['privates', '.service_locator.laXNkD5', 'get_ServiceLocator_LaXNkD5Service', true],
            'App\\Controller\\ApiController:addGroupTag' => ['privates', '.service_locator.CFXoCYH', 'get_ServiceLocator_CFXoCYHService', true],
            'App\\Controller\\ApiController:addPromo' => ['privates', '.service_locator.nWE6WNn', 'get_ServiceLocator_NWE6WNnService', true],
            'App\\Controller\\ApiController:addREferentiels' => ['privates', '.service_locator.9eJSN7i', 'get_ServiceLocator_9eJSN7iService', true],
            'App\\Controller\\ApiController:addUser' => ['privates', '.service_locator.DxkX6ZN', 'get_ServiceLocator_DxkX6ZNService', true],
            'App\\Controller\\ApiController:editUser' => ['privates', '.service_locator..BC20In', 'get_ServiceLocator__BC20InService', true],
            'App\\Controller\\LivrablesController:UpdateLivrable' => ['privates', '.service_locator.19ps0qC', 'get_ServiceLocator_19ps0qCService', true],
            'App\\Controller\\LivrablesController:addLivrable' => ['privates', '.service_locator.19ps0qC', 'get_ServiceLocator_19ps0qCService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\ApiController::ApprenantAddedByFormateur' => '?',
            'App\\Controller\\ApiController::GroupeCompetence' => '?',
            'App\\Controller\\ApiController::UpdatePormo' => '?',
            'App\\Controller\\ApiController::UpdateReferentiel' => '?',
            'App\\Controller\\ApiController::addGroupTag' => '?',
            'App\\Controller\\ApiController::addPromo' => '?',
            'App\\Controller\\ApiController::addREferentiels' => '?',
            'App\\Controller\\ApiController::addUser' => '?',
            'App\\Controller\\ApiController::editUser' => '?',
            'App\\Controller\\LivrablesController::UpdateLivrable' => '?',
            'App\\Controller\\LivrablesController::addLivrable' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ApiController:ApprenantAddedByFormateur' => '?',
            'App\\Controller\\ApiController:GroupeCompetence' => '?',
            'App\\Controller\\ApiController:UpdatePormo' => '?',
            'App\\Controller\\ApiController:UpdateReferentiel' => '?',
            'App\\Controller\\ApiController:addGroupTag' => '?',
            'App\\Controller\\ApiController:addPromo' => '?',
            'App\\Controller\\ApiController:addREferentiels' => '?',
            'App\\Controller\\ApiController:addUser' => '?',
            'App\\Controller\\ApiController:editUser' => '?',
            'App\\Controller\\LivrablesController:UpdateLivrable' => '?',
            'App\\Controller\\LivrablesController:addLivrable' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
