<?php

namespace ContainerXe6KQ67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CI2vR2_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CI2vR2.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CI2vR2.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ApiController::ApprenantAddedByFormateur' => ['privates', '.service_locator.DxkX6ZN', 'get_ServiceLocator_DxkX6ZNService', true],
            'App\\Controller\\ApiController::GroupeCompetence' => ['privates', '.service_locator.VJywsi3', 'get_ServiceLocator_VJywsi3Service', true],
            'App\\Controller\\ApiController::addUser' => ['privates', '.service_locator.DxkX6ZN', 'get_ServiceLocator_DxkX6ZNService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\ApiController:ApprenantAddedByFormateur' => ['privates', '.service_locator.DxkX6ZN', 'get_ServiceLocator_DxkX6ZNService', true],
            'App\\Controller\\ApiController:GroupeCompetence' => ['privates', '.service_locator.VJywsi3', 'get_ServiceLocator_VJywsi3Service', true],
            'App\\Controller\\ApiController:addUser' => ['privates', '.service_locator.DxkX6ZN', 'get_ServiceLocator_DxkX6ZNService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\ApiController::ApprenantAddedByFormateur' => '?',
            'App\\Controller\\ApiController::GroupeCompetence' => '?',
            'App\\Controller\\ApiController::addUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ApiController:ApprenantAddedByFormateur' => '?',
            'App\\Controller\\ApiController:GroupeCompetence' => '?',
            'App\\Controller\\ApiController:addUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
