<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXe6KQ67\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXe6KQ67/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXe6KQ67.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXe6KQ67\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXe6KQ67\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xe6KQ67',
    'container.build_id' => '12df6203',
    'container.build_time' => 1606302302,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXe6KQ67');
