<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUqqvH5F\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUqqvH5F/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUqqvH5F.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUqqvH5F\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUqqvH5F\App_KernelDevDebugContainer([
    'container.build_hash' => 'UqqvH5F',
    'container.build_id' => 'a8de5864',
    'container.build_time' => 1606852151,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUqqvH5F');
